ccflags-y += -Iarch/arm/mach-msm

obj-$(CONFIG_MACH_LGE) += devices_lge.o
#obj-$(CONFIG_MACH_LGE) += lge_earjack_debugger.o
obj-$(CONFIG_MACH_DORY) += board-8026-dory.o
obj-$(CONFIG_MACH_DORY) += board-8026-dory-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_HAMMERHEAD) += board-8974-hammerhead.o
obj-$(CONFIG_MACH_MSM8974_HAMMERHEAD) += board-8974-hammerhead-gpiomux.o
obj-$(CONFIG_LGE_BLUETOOTH) += board-8974-rfkill.o
obj-$(CONFIG_WIFI_CONTROL_FUNC) += board-wifi-bcm.o
obj-$(CONFIG_LGE_BLUETOOTH) += board-8026-dory-rfkill.o
obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o
